[server]
port = 4501
domain="localhost"

[database]
host = "localhost"
port = 5432
user = "asteroidgazer"
password = ""
name = "asteroidgazer"
ssl = "disabled"

[actor]
privatekey = "/etc/asteroidgazer/actor.pem"
icon = ""
image = ""
summary = ""
